export const ESOCIAL_TABELA3 = [
  { codigo: '1000', descricao: 'Remuneração periódica - salário' },
  { codigo: '1010', descricao: 'Salário mensal' },
  { codigo: '1020', descricao: 'Salário por hora' },
  { codigo: '1040', descricao: 'Comissão' },
  { codigo: '1100', descricao: 'Gratificação' },
  { codigo: '1200', descricao: 'Adicional de insalubridade' },
  { codigo: '1210', descricao: 'Adicional de periculosidade' },
  { codigo: '1220', descricao: 'Adicional noturno' },
  { codigo: '1230', descricao: 'Adicional de transferência' },
  { codigo: '1320', descricao: 'Horas extras' },
  { codigo: '1350', descricao: 'DSR sobre variáveis' },
  { codigo: '1360', descricao: 'Descanso semanal remunerado' },
  { codigo: '1500', descricao: 'Diárias para viagem' },
  { codigo: '1600', descricao: 'Abono' },
  { codigo: '1700', descricao: 'Salário maternidade' },
  { codigo: '1800', descricao: 'Auxílio doença' },
  { codigo: '2100', descricao: '13º salário integral' },
  { codigo: '2101', descricao: '13º salário proporcional' },
  { codigo: '3500', descricao: 'Férias - período integral' },
  { codigo: '3501', descricao: 'Férias proporcionais' },
  { codigo: '3505', descricao: '1/3 constitucional de férias' },
  { codigo: '5001', descricao: 'INSS descontado do trabalhador' },
  { codigo: '5002', descricao: 'IRRF descontado do trabalhador' },
  { codigo: '5003', descricao: 'Contribuição sindical laboral' },
  { codigo: '5010', descricao: 'Vale transporte - desconto' },
  { codigo: '5020', descricao: 'Vale refeição - desconto' },
  { codigo: '5050', descricao: 'Plano de saúde - desconto' },
  { codigo: '5060', descricao: 'Adiantamento salarial' },
  { codigo: '5070', descricao: 'Pensão alimentícia' },
  { codigo: '6000', descricao: 'FGTS mensal' },
  { codigo: '6010', descricao: 'FGTS 13º salário' },
  { codigo: '6020', descricao: 'FGTS férias' },
  { codigo: '6100', descricao: 'Multa FGTS 40%' },
  { codigo: '7000', descricao: 'Saldo de salário' },
  { codigo: '7010', descricao: 'Aviso prévio indenizado' },
  { codigo: '7020', descricao: '13º salário rescisório' },
  { codigo: '7030', descricao: 'Férias indenizadas' },
  { codigo: '7040', descricao: '1/3 férias indenizadas' },
  { codigo: '9000', descricao: 'Vale transporte' },
  { codigo: '9010', descricao: 'Vale refeição/alimentação' },
  { codigo: '9020', descricao: 'Plano de saúde' },
  { codigo: '9030', descricao: 'Auxílio educação' },
  { codigo: '9040', descricao: 'Auxílio creche' },
]
